# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ARTICLE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ARTICLE_TITLE', models.TextField()),
                ('ARTICLE_AUTHOR', models.CharField(max_length=20)),
                ('ARTICLE_CONTENT', models.TextField()),
                ('ADD_DATETIME', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('COMMENT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ARTICLE_ID', models.IntegerField()),
                ('COMMENT_AUTHOR', models.CharField(max_length=20)),
                ('COMMENT_CNTENT', models.TextField()),
                ('ADD_DATETIME', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('MUSIC_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MUSIC_NAME', models.CharField(max_length=20)),
                ('MUSIC_LIST', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('PLAN_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PLAN_USER', models.CharField(max_length=20)),
                ('PLAN_NAME', models.TextField()),
                ('ADD_DATETIME', models.DateTimeField(auto_now=True)),
                ('RUN_DATETIME', models.DateTimeField()),
                ('PLACE', models.TextField()),
                ('PARTNER', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('SESSION_ID', models.UUIDField(primary_key=True, serialize=False)),
                ('SESSION_NAME', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('USER_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('USER_NAME', models.TextField()),
                ('USER_PASSWORD', models.CharField(max_length=200)),
                ('USER_SCHOOL', models.TextField()),
                ('USER_PHONE', models.CharField(max_length=11)),
                ('USER_EMAIL', models.EmailField(max_length=254)),
            ],
        ),
    ]
