# -*- coding: utf-8 -*-
'''
Create on Jan 1st 2018
@Author KEYS
'''
class Constant(object):

    REGISTER = '[REGISTER]'
    LOGOUT = '[LOGOUT]'
    SAVESESSION = '[SAVESESSION]'
    CREATEPLAN = '[CREATEPLAN]'
    UPDATEPLAN = '[UPDATEPLAN]'
    DELETEPLAN = '[DELETEPLAN]'
    CREATEMUSICLIST = '[CREATEMUSICLIST]'
    UPDATEMUSICLIST = '[CREATEMUSICLIST]'
    DELETEMUSICLIST = '[CREATEMUSICLIST]'
    CREATEARTICLE = '[CREATEARTICLE]'
    UPDATEARTICLE = '[CREATEARTICLE]'
    DELETEARTICLE = '[CREATEARTICLE]'
    CREATECOMMENT = '[CREATECOMMENT]'
    DELETECOMMENT = '[DELETECOMMENT]'

    ERROR_DATABASE = 'Database operation is abnormal'
    ERROR_REGISTER_EXISTS = 'This user id is already registered'
    ERROR_LOGIN_NOLOGIN = 'This user is not logged in'
    ERROR_LOGIN_HASOTHERLOGIN = 'There are already other user logged in'
    ERROR_LOGIN_NOEXISTS = 'This user is not registered'
    ERROR_LOGIN_INCORRECT = 'Username or password is incorrect'
    ERROR_LOGIN_HASLOGIN = 'This user is already logged in'
    ERROR_PLAN_CONFLICT = 'The plan is in conflict'
    ERROR_PLAN_NOEXISTS = 'The plan is not created'
    ERROR_MUSICLIST_CONFLICT = 'The music list is in conflict'
    ERROR_MUSICLIST_NOEXISTS = 'The music list does not exist'
    ERROR_ARTICLE_CONFLICT = 'The article is in conflict'
    ERROR_ARTICLE_NOEXISTS = 'The article does not exist'
    ERROR_COMMENT_NOEXISTS = 'The comment does not exist'

    SUCCESS_REGISTER = 'Registered successfully'
    SUCCESS_LOGIN = 'Login successful'
    SUCCESS_LOGOUT = 'Logout successful'
    SUCCESS_GETUSERINFO = 'Get the user information successfully'
    SUCCESS_CREATEPLAN = 'Create plan successfully'
    SUCCESS_UPDATEPLAN = 'Update plan successfully'
    SUCCESS_DELETEPLAN = 'Delete plan successfully'
    SUCCESS_GETALLPLANS = 'Get all plans successfully'
    SUCCESS_CREATEMUSICLIST = 'Create music list successfully'
    SUCCESS_UPDATEMUSICLIST = 'Update music list successfully'
    SUCCESS_DELETEMUSICLIST = 'Delete music list successfully'
    SUCCESS_GETMUSICLIST = 'Get musi clist successfully'
    SUCCESS_CREATEARTICLE = 'Create article successfully'
    SUCCESS_UPDATEARTICLE = 'Update article successfully'
    SUCCESS_DELETEARTICLE = 'Delete article successfully'
    SUCCESS_GETALLARTICLE = 'Get all artciles successfully'
    SUCCESS_CREATECOMMENT = 'Create comment successfully'
    SUCCESS_DELETECOMMENT = 'Delete comment successfully'
    SUCCESS_GETALLCOMMENTS = 'Get all comments successfully'

    FAIL_REGISTER = 'Fail to register'
    FAIL_LOGIN = 'Fail to login'
    FAIL_LOGOUT = 'Failed to logout'
    FAIL_GETUSERINFO = 'Failed to get user information'
    FAIL_CREATEPLAN = 'Failed to create plan'
    FAIL_DELETEPLAN = 'Failed to delete plan'
    FAIL_UPDATEPLAN = 'Failed to update plan'
    FAIL_GETALLPLANS = 'Failed to get all plans'
    FAIL_CREATEMUSICLIST = 'Failed to create music list'
    FAIL_UPDATEMUSICLIST = 'Failed to update music list'
    FAIL_DELETEMUSICLIST = 'Failed to delete music list'
    FAIL_GETMUSICLIST = 'Failed to get music list'
    FAIL_CREATEARTICLE = 'Failed to create article'
    FAIL_UPDATEARTICLE = 'Failed to update article'
    FAIL_DELETEARTICLE = 'Failed to delete article'
    FAIL_GETALLARTICLE = 'Failed to get all artciles'
    FAIL_CREATECOMMENT = 'Failed to create comment'
    FAIL_DELETECOMMENT = 'Failed to delete comment'
    FAIL_GETALLCOMMENTS = 'Failed to get all comments'
